name: dbt-ci

on:
  pull_request:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt

          echo '${{ secrets.DBT_SERVICE_ACCOUNT }}' > ~/.dbt/service-account.json

          cat > ~/.dbt/profiles.yml << EOF
          healthcare_analytics:
            outputs:
              ci:
                type: bigquery
                method: service-account
                project: healthcare-dbt
                dataset: ci
                threads: 1
                keyfile: ~/.dbt/service-account.json
                location: US
                priority: interactive
                job_retries: 1
                job_execution_timeout_seconds: 300
            target: ci
          EOF

      - name: dbt debug
        run: |
          dbt debug